// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fgyoexlosyvvgumpzgwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZneW9leGxvc3l2dmd1bXB6Z3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjQ3OTIsImV4cCI6MjA3MDI0MDc5Mn0.2y4s9BkFC-xqeko4h0uDDM8glYQJu1OLqpZWlP0067U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Prevent aggressive session refresh on visibility change
    storageKey: 'trac-q-auth',
  }
});